-- ============================================================
-- Migration_DataAwal_Part2.sql
-- Lanjutan migrasi setelah error di AST-0077
-- Baris 590: #1048 - Column 'tanggal_registrasi' cannot be null
-- ============================================================
-- KONTEKS:
-- - Eksekusi Migration_DataAwal.sql terhenti di AST-0077
-- - Data Master + AST-0001..AST-0076 sudah masuk DB
-- - File ini melanjutkan sisa data yang belum masuk
--
-- PERBAIKAN:
-- - tanggal_registrasi NULL -> '2024-01-01' (default aman)
-- - id_kondisi NULL -> 1 (Baik) jika masih NULL
-- - Status enum sudah divalidasi: Aktif/Dipinjam/Di Gudang
-- - Tidak ada DELETE/TRUNCATE/ALTER/AUTO_INCREMENT/Master
--
-- ISI:
-- - aset: 29 rows (AST-0077 s/d AST-0105)
-- - aset_habis_pakai: 17 rows (HP-0099 s/d HP-0115) - yang memiliki NULL tanggal
--   Total habis di file asli: 115 rows (HP-0001..HP-0115)
--   Jika habis_pakai belum tereksekusi sama sekali, gunakan file *_FULL atau jalankan semua 115
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- SISA ASET: AST-0077 s/d AST-0105 (29 rows)
-- Fix: tanggal_registrasi NULL -> '2024-01-01', id_kondisi NULL -> 1
-- ============================================================

INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (77, 'AST-0077', 176, 12, 1, NULL, 1, 'INV-0077', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (78, 'AST-0078', 177, NULL, 2, NULL, 2, 'INV-0078', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (79, 'AST-0079', 179, 10, 5, 5, 5, 'INV-0079', 'Aktif', 1, '2024-01-01', 'Dipakai Nesabastore 1');
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (80, 'AST-0080', 180, 10, 9, 5, 9, 'INV-0080', 'Aktif', 1, '2024-01-01', 'Dipakai Nesabastore 1');
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (81, 'AST-0081', 194, NULL, 11, NULL, 11, 'INV-0081', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (82, 'AST-0082', 195, NULL, 5, 2, 5, 'INV-0082', 'Aktif', 1, '2024-01-01', 'milik Aula');
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (83, 'AST-0083', 196, NULL, 5, 2, 5, 'INV-0083', 'Aktif', 1, '2022-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (84, 'AST-0084', 197, NULL, 5, 2, 5, 'INV-0084', 'Aktif', 1, '2023-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (85, 'AST-0085', 200, NULL, 2, NULL, 2, 'INV-0085', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (86, 'AST-0086', 201, NULL, 3, NULL, 3, 'INV-0086', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (87, 'AST-0087', 202, NULL, 3, NULL, 3, 'INV-0087', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (88, 'AST-0088', 203, NULL, 3, NULL, 3, 'INV-0088', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (89, 'AST-0089', 204, NULL, 3, NULL, 3, 'INV-0089', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (90, 'AST-0090', 205, NULL, 2, NULL, 2, 'INV-0090', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (91, 'AST-0091', 206, NULL, 3, NULL, 3, 'INV-0091', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (92, 'AST-0092', 207, NULL, 4, NULL, 4, 'INV-0092', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (93, 'AST-0093', 208, NULL, 3, NULL, 3, 'INV-0093', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (94, 'AST-0094', 209, 15, 3, NULL, 3, 'INV-0094', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (95, 'AST-0095', 210, NULL, 4, NULL, 4, 'INV-0095', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (96, 'AST-0096', 211, 15, 4, NULL, 4, 'INV-0096', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (97, 'AST-0097', 212, NULL, 4, NULL, 4, 'INV-0097', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (98, 'AST-0098', 213, NULL, 4, NULL, 4, 'INV-0098', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (99, 'AST-0099', 214, NULL, 4, NULL, 4, 'INV-0099', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (100, 'AST-0100', 215, NULL, 4, NULL, 4, 'INV-0100', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (101, 'AST-0101', 216, 15, 4, NULL, 4, 'INV-0101', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (102, 'AST-0102', 217, NULL, 5, NULL, 5, 'INV-0102', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (103, 'AST-0103', 218, 6, 5, 2, 5, 'INV-0103', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (104, 'AST-0104', 219, 13, 6, 5, 6, 'INV-0104', 'Aktif', 1, '2024-01-01', NULL);
INSERT INTO `aset` (`kode_barang`, `kode_barang2`, `id_master_barang`, `id_jurusan`, `id_ruang`, `id_lemari`, `id_lokasi`, `kode_inventaris`, `status`, `id_kondisi`, `tanggal_registrasi`, `keterangan`) VALUES (105, 'AST-0105', 220, 15, 5, 2, 5, 'INV-0105', 'Aktif', 1, '2023-01-01', NULL);

-- ============================================================
-- SISA ASET HABIS PAKAI: HP-0099 s/d HP-0115 (17 rows)
-- Kondisi: memiliki tanggal_registrasi NULL sebelumnya, sekarang fix -> '2024-01-01'
-- Jika HP-0001..HP-0098 belum masuk sama sekali, jalankan juga block di bawah (sudah difix)
-- ============================================================

INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0099', 175, 4, 4, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0100', 178, 10, 10, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0101', 181, 2, 2, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0102', 182, 4, 4, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0103', 183, 3, 3, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'TouchScreen', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0104', 184, 40, 18, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'Stok 20', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0105', 185, 30, 15, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0106', 186, 10, 15, NULL, NULL, NULL, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0107', 187, 1, 1, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0108', 188, 1, 1, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0109', 189, 4, 4, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0110', 190, 1, 4, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0111', 191, 20, 20, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0112', 192, 2, 2, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0113', 193, 1, 1, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0114', 198, 3, 3, NULL, 8, 8, 'Aktif', '2024-01-01', 'Stok 3', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0115', 199, 3, 3, NULL, NULL, NULL, 'Aktif', '2024-01-01', NULL, 0);

-- ============================================================
-- OPSIONAL: Jika aset_habis_pakai BELUM TEREKSEKUSI sama sekali (115 rows)
-- Uncomment block di bawah ini untuk menjalankan semua habis pakai yang sudah difix
-- ============================================================
-- (Dibiarkan comment agar tidak duplicate jika HP-0001..HP-0098 sudah masuk)
-- Uncomment jika diperlukan:
/*
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0001', 4, 1, 47, NULL, 8, 8, 'Aktif', '2017-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0002', 9, 2, 2, NULL, 8, 8, 'Aktif', '2021-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0003', 10, 1, 1, NULL, 5, 5, 'Aktif', '2021-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0004', 17, 1, 1, NULL, 1, 1, 'Aktif', '2021-01-01', 'Untuk Monitor CCTV', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0005', 18, 1, 1, NULL, NULL, NULL, 'Aktif', '2021-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0006', 20, 5, 5, NULL, NULL, NULL, 'Aktif', '2022-01-01', 'Terpakai di Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0007', 21, 8, 8, NULL, 5, 5, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0008', 22, 4, 4, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0009', 23, 1, 1, 15, 5, 5, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0010', 24, 1, 1, 15, 1, 1, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0011', 27, 1, 1, NULL, 5, 5, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0012', 28, 8, 8, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0013', 30, 2, 2, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0014', 31, 1, 1, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0015', 32, 1, 1, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0016', 33, 1, 1, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0017', 34, 1, 1, NULL, 8, 8, 'Aktif', '2022-01-01', 'Stok 1', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0018', 35, 1, 1, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0019', 36, 1, 1, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0020', 37, 1, 1, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0021', 38, 4, 4, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0022', 39, 4, 4, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0023', 40, 10, 10, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0024', 42, 1, 1, NULL, NULL, NULL, 'Aktif', '2022-01-01', 'di PC Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0025', 43, 2, 2, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0026', 44, 1, 1, NULL, 4, 4, 'Aktif', '2022-01-01', 'Diganti Epson L121', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0027', 45, 10, 10, NULL, NULL, NULL, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0028', 46, 2, 2, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0029', 47, 1, 1, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0030', 48, 1, 1, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0031', 49, 1, 1, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0032', 50, 1, 1, NULL, 8, 8, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0033', 54, 2, 2, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0034', 58, 1, 1, NULL, NULL, NULL, 'Aktif', '2022-01-01', 'Untuk Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0035', 59, 8, 8, NULL, 4, 4, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0036', 60, 2, 2, NULL, 10, 10, 'Aktif', '2022-01-01', 'Pengajuan Asli Daikin FTC15NV14 / FTC 15 1/2 PK', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0037', 61, 2, 2, NULL, 1, 1, 'Aktif', '2022-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0038', 65, 1, 1, NULL, 1, 1, 'Aktif', '2023-01-01', 'Dipinjam Bu Sa''diyah', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0039', 72, 1, 1, NULL, 1, 1, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0040', 74, 3, 3, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Habis', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0041', 75, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Habis', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0042', 76, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Habis', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0043', 77, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Habis', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0044', 78, 2, 2, 6, 1, 1, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0045', 80, 4, 1, 6, 1, 1, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0046', 81, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0047', 82, 11, 11, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Dipasang di PC Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0048', 83, 1, 1, 6, 1, 1, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0049', 85, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', 'Dipasang di CCTV', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0050', 86, 1, 1, NULL, NULL, NULL, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0051', 90, 1, 3, NULL, 1, 1, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0052', 91, 3, 3, NULL, 5, 5, 'Aktif', '2023-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0053', 98, 5, 0, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'Dipasang di PC Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0054', 99, 6, 0, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'Dipasang di PC Lab', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0055', 100, 1, 1, NULL, NULL, NULL, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0056', 101, 4, 5, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0057', 102, 5, 5, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0058', 105, 10, 0, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'Dipasang di Labtop', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0059', 106, 5, 5, NULL, NULL, NULL, 'Aktif', '2024-01-01', 'Dipasang di Labtop', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0060', 107, 5, 5, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0061', 108, 5, 5, NULL, 1, 1, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0062', 116, 1, 1, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0063', 117, 1, 1, NULL, 8, 8, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0064', 118, 1, 0, NULL, 1, 1, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0065', 122, 1, 1, NULL, 5, 5, 'Aktif', '2024-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0066', 123, 1, 1, NULL, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0067', 141, 1, 1, NULL, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0068', 142, 4, 4, NULL, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0069', 143, 1, 1, 6, 1, 1, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0070', 144, 1, 1, 6, 4, 4, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0071', 145, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0072', 146, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0073', 147, 3, 3, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0074', 148, 1, 1, NULL, NULL, NULL, 'Aktif', '2025-01-01', 'Dipasang P Wildam', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0075', 149, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0076', 150, 8, 8, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0077', 151, 1, 1, 6, NULL, NULL, 'Aktif', '2025-01-01', 'Laptop HP Hitam', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0078', 152, 9, 9, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0079', 153, 1, 1, 6, NULL, NULL, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0080', 154, 4, 4, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0081', 155, 5, 5, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0082', 156, 1, 1, 6, NULL, NULL, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0083', 157, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0084', 158, 2, 2, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0085', 159, 2, 2, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0086', 160, 2, 2, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0087', 161, 2, 2, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0088', 162, 2, 2, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0089', 163, 5, 5, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0090', 164, 5, 5, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0091', 165, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0092', 166, 5, 5, 6, NULL, NULL, 'Aktif', '2025-01-01', 'Untuk Kabel Koloran di Kelas', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0093', 167, 1, 1, 6, NULL, NULL, 'Aktif', '2025-01-01', 'Untuk Kabel Koloran di Kelas', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0094', 168, 5, 5, 6, NULL, NULL, 'Aktif', '2025-01-01', 'Untuk Kabel Koloran di Kelas', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0095', 169, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0096', 170, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0097', 171, 1, 1, 6, NULL, NULL, 'Aktif', '2025-01-01', 'Dipakai Praktik', 0);
INSERT INTO `aset_habis_pakai` (`kode_barang`, `id_master_barang`, `stok`, `stok_aktual`, `id_jurusan`, `id_ruang`, `id_lokasi`, `status`, `tanggal_registrasi`, `keterangan`, `is_returnable`) VALUES ('HP-0098', 172, 1, 1, 6, 8, 8, 'Aktif', '2025-01-01', NULL, 0);
*/

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- SELESAI Part 2
-- Verifikasi:
-- SELECT COUNT(*) FROM aset; -- harus 105 total (76+29)
-- SELECT COUNT(*) FROM aset WHERE kode_barang2 >= 'AST-0077'; -- harus 29
-- SELECT COUNT(*) FROM aset_habis_pakai; -- harus 115 jika full, atau 17 jika hanya sisa
-- ============================================================